###

GET http://localhost:3000/api/posts HTTP/1.1

###

GET http://localhost:3000/api/posts/67b24851cf017847c38473c1 HTTP/1.1

###

POST http://localhost:3000/api/posts HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2M2MzMwMDNmMDU3YjFkMDc1ZWI1Y2YiLCJpYXQiOjE3NDEzNDY0MjEsImV4cCI6MTc0MTQzMjgyMX0.AFGLWakeB469iXlsg-YTD0z3vy0vEdWuyelKJ_YXnxE

{
    "title": "First Post",
    "content": "This is a second post"
}

###

PATCH http://localhost:3000/api/posts/67abb92c629bfa5565edbe7d HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2M2MzMwMDNmMDU3YjFkMDc1ZWI1Y2YiLCJpYXQiOjE3NDEzNDY0MjEsImV4cCI6MTc0MTQzMjgyMX0.AFGLWakeB469iXlsg-YTD0z3vy0vEdWuyelKJ_YXnxE

{
    "title": "Second Post",
    "content": "This is a third post edited"
} 

###

DELETE http://localhost:3000/api/posts/67abb92c629bfa5565edbe7d HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2M2MzMwMDNmMDU3YjFkMDc1ZWI1Y2YiLCJpYXQiOjE3NDEzNDY0MjEsImV4cCI6MTc0MTQzMjgyMX0.AFGLWakeB469iXlsg-YTD0z3vy0vEdWuyelKJ_YXnxE
 